-- GS Tours CRM — per-user JSON-blob entities, matching the original SQLite schema.
-- Composite PK (user_id, id) so workspaces never collide across accounts.

create table if not exists gst_companies (
  user_id    text not null,
  id         text not null,
  name       text,
  data       text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);
create index if not exists gst_companies_user_idx on gst_companies (user_id);

create table if not exists gst_vendors (
  user_id    text not null,
  id         text not null,
  name       text,
  data       text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);
create index if not exists gst_vendors_user_idx on gst_vendors (user_id);

create table if not exists gst_contacts (
  user_id    text not null,
  id         text not null,
  name       text,
  data       text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);
create index if not exists gst_contacts_user_idx on gst_contacts (user_id);

create table if not exists gst_queries (
  user_id    text not null,
  id         text not null,
  ref        text,
  company    text,
  stage      text,
  data       text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);
create index if not exists gst_queries_user_idx on gst_queries (user_id);

create table if not exists gst_bookings (
  user_id    text not null,
  id         text not null,
  ref        text,
  company    text,
  status     text,
  trip_date  text,
  data       text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);
create index if not exists gst_bookings_user_idx on gst_bookings (user_id);

create table if not exists gst_invoices (
  user_id    text not null,
  id         text not null,
  number     text,
  company    text,
  status     text,
  data       text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);
create index if not exists gst_invoices_user_idx on gst_invoices (user_id);

create table if not exists gst_settings (
  user_id    text primary key,
  data       text not null,
  updated_at timestamptz not null default now()
);

create table if not exists gst_meta (
  user_id    text primary key,
  data       text not null,
  updated_at timestamptz not null default now()
);

-- Append-only. Never truncate automatically. Snapshot is the pre-write record.
create table if not exists gst_audit_log (
  id         integer generated by default as identity primary key,
  user_id    text not null,
  entity     text not null,
  entity_id  text,
  action     text not null,
  snapshot   text,
  at         timestamptz not null default now()
);
create index if not exists gst_audit_user_idx on gst_audit_log (user_id, at desc);
