import { DEFAULT_SETTINGS } from "./defaults";
import type {
  BookingRecord,
  CompanyRecord,
  ContactLogEntry,
  ContactRecord,
  DriverRecord,
  InvoiceRecord,
  QueryRecord,
  VehicleRecord,
  VendorRecord,
  Workspace,
} from "./types";

const BY = "Sample workspace";
const AT = "2026-09-12T09:00:00.000Z";

function log(
  id: string,
  date: string,
  direction: ContactLogEntry["direction"],
  channel: ContactLogEntry["channel"],
  note: string,
): ContactLogEntry {
  return { id, date, direction, channel, note, logged: `${date}T10:00:00.000Z` };
}

const companies: CompanyRecord[] = [
  {
    id: "co_india",
    name: "Embassy of India",
    type: "Embassy / Diplomatic",
    street: "Buitenrustweg 2",
    postcode: "2517 KD",
    city: "Den Haag",
    country: "Nederland",
    vat: "",
    kvk: "",
    termsDays: 30,
    invoiceEmail: "cons.thehague@mea.gov.in",
    phone: "+31 70 346 9771",
    contactName: "Mr. R. Kumar",
    extraHourRate: 42,
    extraKmRate: 1.2,
    notes: "Tender HAG/873/2/2021. Always bill extra time in commenced 30-min blocks. Booked-for name on every line.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_gemeente",
    name: "Gemeente Den Haag",
    type: "Corporate",
    street: "Spui 70",
    postcode: "2511 BT",
    city: "Den Haag",
    country: "Nederland",
    vat: "NL0016.90.962.B01",
    kvk: "51477950",
    termsDays: 30,
    invoiceEmail: "facturen@denhaag.nl",
    phone: "+31 70 353 3000",
    contactName: "Inkoop Mobiliteit",
    extraHourRate: 55,
    extraKmRate: 1.45,
    notes: "PO required on every invoice.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_corendon",
    name: "Corendon Travel",
    type: "Travel agent",
    street: "Corendon Boulevard 1",
    postcode: "2132 WT",
    city: "Hoofddorp",
    country: "Nederland",
    vat: "NL8098.12.334.B01",
    kvk: "34079821",
    termsDays: 21,
    invoiceEmail: "ops@corendon.nl",
    phone: "+31 23 751 0600",
    contactName: "Lisa Vermeer",
    extraHourRate: null,
    extraKmRate: null,
    notes: "Keukenhof and day-trip programme, spring peak.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_unilever",
    name: "Unilever Nederland",
    type: "Corporate",
    street: "Weena 455",
    postcode: "3013 AL",
    city: "Rotterdam",
    country: "Nederland",
    vat: "NL0018.76.221.B01",
    kvk: "24040011",
    termsDays: 30,
    invoiceEmail: "ap@unilever.com",
    phone: "+31 10 439 4911",
    contactName: "Facilities desk",
    extraHourRate: 48,
    extraKmRate: 1.35,
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_sophie",
    name: "Sophie van Dijk",
    type: "Private",
    street: "Prins Hendrikstraat 18",
    postcode: "2518 HZ",
    city: "Den Haag",
    country: "Nederland",
    vat: "",
    kvk: "",
    termsDays: 0,
    invoiceEmail: "sophie.vandijk@icloud.com",
    phone: "+31 6 2188 4401",
    contactName: "Sophie van Dijk",
    extraHourRate: null,
    extraKmRate: null,
    notes: "Wedding at Kasteel De Wittenburg, Wassenaar. Private individual — no VAT number.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_desindes",
    name: "Hotel Des Indes",
    type: "MICE / Events",
    street: "Lange Voorhout 54–56",
    postcode: "2514 EG",
    city: "Den Haag",
    country: "Nederland",
    vat: "NL8091.22.118.B01",
    kvk: "27112409",
    termsDays: 14,
    invoiceEmail: "events@hoteldesindes.nl",
    phone: "+31 70 361 2345",
    contactName: "Concierge",
    extraHourRate: 52,
    extraKmRate: 1.4,
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_shell",
    name: "Shell Nederland",
    type: "Corporate",
    street: "Carel van Bylandtlaan 16",
    postcode: "2596 HR",
    city: "Den Haag",
    country: "Nederland",
    vat: "NL0015.63.774.B01",
    kvk: "27002688",
    termsDays: 30,
    invoiceEmail: "invoices-nl@shell.com",
    phone: "+31 70 377 9111",
    contactName: "Travel office",
    extraHourRate: 50,
    extraKmRate: 1.3,
    notes: "Airport shuttles AMS / RTM.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_ukemb",
    name: "British Embassy The Hague",
    type: "Embassy / Diplomatic",
    street: "Lange Voorhout 10",
    postcode: "2514 ED",
    city: "Den Haag",
    country: "Nederland",
    vat: "",
    kvk: "",
    termsDays: 30,
    invoiceEmail: "ukinnl.finance@fcdo.gov.uk",
    phone: "+31 70 427 0427",
    contactName: "Transport desk",
    extraHourRate: 45,
    extraKmRate: 1.25,
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "co_eventure",
    name: "Eventure MICE",
    type: "MICE / Events",
    street: "Weteringschans 165",
    postcode: "1017 XD",
    city: "Amsterdam",
    country: "Nederland",
    vat: "NL8544.21.009.B01",
    kvk: "64322190",
    termsDays: 14,
    invoiceEmail: "billing@eventure.nl",
    phone: "+31 20 330 8810",
    contactName: "Mila de Boer",
    extraHourRate: null,
    extraKmRate: null,
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
];

const vendors: VendorRecord[] = [
  {
    id: "ve_valk",
    name: "Van der Valk Coach",
    type: "Coach operator",
    standing: "Preferred",
    contactStatus: "Agreed",
    city: "Voorschoten",
    street: "Baron de Coubertinlaan 2",
    postcode: "2252 BA",
    country: "Nederland",
    phone: "+31 71 560 2000",
    invoiceEmail: "planning@valkcoach.nl",
    contactName: "Henk Valk",
    kvk: "28044112",
    rates: [
      { service: "Coach 50", basis: "Per day", price: 890, validUntil: "2026-12-31" },
      { service: "Midi coach 35", basis: "Per day", price: 720, validUntil: "2026-12-31" },
    ],
    notes: "Cover for GS overflow. 48h notice preferred.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "ve_tcdh",
    name: "Taxi Centrale Den Haag",
    type: "Taxi / sedan",
    standing: "Approved",
    contactStatus: "Rate received",
    city: "Den Haag",
    street: "Binckhorstlaan 123",
    postcode: "2516 BA",
    country: "Nederland",
    phone: "+31 70 390 7777",
    invoiceEmail: "account@tcdh.nl",
    contactName: "Dispatch",
    kvk: "27199801",
    rates: [{ service: "Sedan airport", basis: "Per transfer", price: 95, validUntil: "2026-12-31" }],
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "ve_jan",
    name: "Jan Bakker (freelance)",
    type: "Driver (freelance)",
    standing: "Preferred",
    contactStatus: "Agreed",
    city: "Rijswijk",
    street: "Generaal Spoorlaan 8",
    postcode: "2281 AT",
    country: "Nederland",
    phone: "+31 6 5321 7780",
    invoiceEmail: "jan.bakker.driver@gmail.com",
    contactName: "Jan Bakker",
    kvk: "72100344",
    rates: [{ service: "Driver day", basis: "Per day", price: 280, validUntil: "2026-12-31" }],
    notes: "D/D+E. Speaks EN/NL/DE.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "ve_keuken",
    name: "Keukenhof",
    type: "Attraction / experience",
    standing: "Approved",
    contactStatus: "Agreed",
    city: "Lisse",
    street: "Stationsweg 166A",
    postcode: "2161 AM",
    country: "Nederland",
    phone: "+31 252 465 555",
    invoiceEmail: "groups@keukenhof.nl",
    contactName: "Group sales",
    kvk: "28084711",
    rates: [{ service: "Group ticket", basis: "Per person", price: 19.5, validUntil: "2026-05-10" }],
    notes: "Coach parking reservation required.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "ve_stena",
    name: "Stena Line",
    type: "Ferry / tolls",
    standing: "Approved",
    contactStatus: "Emailed",
    city: "Hoek van Holland",
    street: "Hoek van Holland Haven",
    postcode: "3151 HR",
    country: "Nederland",
    phone: "+31 174 315 800",
    invoiceEmail: "freight.nl@stenaline.com",
    contactName: "Coach bookings",
    kvk: "24147660",
    rates: [{ service: "Hook–Harwich coach", basis: "Per transfer", price: 420, validUntil: "2026-12-31" }],
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
];

const contacts: ContactRecord[] = [
  {
    id: "ct_kumar",
    name: "Mr. R. Kumar",
    company: "Embassy of India",
    role: "First Secretary (Admin)",
    email: "fsadmin.thehague@mea.gov.in",
    phone: "+31 70 346 9771",
    billsDirectly: "No",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "ct_lisa",
    name: "Lisa Vermeer",
    company: "Corendon Travel",
    role: "Operations",
    email: "l.vermeer@corendon.nl",
    phone: "+31 6 1092 4410",
    billsDirectly: "No",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "ct_sophie",
    name: "Sophie van Dijk",
    company: "Sophie van Dijk",
    role: "Bride",
    email: "sophie.vandijk@icloud.com",
    phone: "+31 6 2188 4401",
    billsDirectly: "Yes - bill them directly",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "ct_mila",
    name: "Mila de Boer",
    company: "Eventure MICE",
    role: "Producer",
    email: "mila@eventure.nl",
    phone: "+31 6 4871 2209",
    billsDirectly: "No",
    updatedAt: AT,
    updatedBy: BY,
  },
];

const queries: QueryRecord[] = [
  {
    id: "q_india",
    ref: "Q-0012",
    brand: "GS Tours",
    source: "Repeat client",
    company: "Embassy of India",
    contactName: "Mr. R. Kumar",
    contactEmail: "fsadmin.thehague@mea.gov.in",
    contactPhone: "+31 70 346 9771",
    tripDate: "2026-09-18",
    pax: 3,
    from: "Buitenrustweg 2, Den Haag",
    to: "Various — ministry round",
    vehicle: "Sedan",
    stage: "Quoted",
    amount: 550,
    owner: "Anouk",
    nextAction: "Send sedan + minivan options for 18 Sep",
    nextActionDate: "2026-09-15",
    lostReason: "",
    notes: "Tender rate card applies. Booked for visiting DDG.",
    log: [
      log("lg1", "2026-09-12", "Outgoing", "Email", "Quoted full-day sedan on tender card, valid for DDG visit."),
      log("lg2", "2026-09-11", "Incoming", "Email", "Need a car 08:00–18:00 on 18 Sep for visiting DDG. Possibly a second V-Class."),
    ],
    created: "2026-09-11",
    moved: "2026-09-12",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "q_keuken",
    ref: "Q-0013",
    brand: "BusBus.nl",
    source: "Travel agent",
    company: "Corendon Travel",
    contactName: "Lisa Vermeer",
    contactEmail: "l.vermeer@corendon.nl",
    contactPhone: "+31 6 1092 4410",
    tripDate: "2026-09-22",
    pax: 48,
    from: "Schiphol Plaza",
    to: "Keukenhof, Lisse",
    vehicle: "Coach 50",
    stage: "Follow-up",
    amount: 980,
    owner: "Anouk",
    nextAction: "Chase confirmation — they had a second operator in play",
    nextActionDate: "2026-09-16",
    lostReason: "",
    notes: "Day trip, 09:00 pickup, 16:30 return. Parking at Keukenhof to be arranged.",
    log: [
      log("lg3", "2026-09-10", "Outgoing", "WhatsApp", "Held Coach 50 for 22 Sep, asked for passenger list."),
      log("lg4", "2026-09-09", "Incoming", "Email", "Request for 48 pax Schiphol–Keukenhof dagtocht."),
    ],
    created: "2026-09-09",
    moved: "2026-09-10",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "q_shell",
    ref: "Q-0014",
    brand: "Taxibedrijf Wassenaar",
    source: "Email",
    company: "Shell Nederland",
    contactName: "Travel office",
    contactEmail: "travel-nl@shell.com",
    contactPhone: "+31 70 377 9111",
    tripDate: "2026-09-19",
    pax: 2,
    from: "Carel van Bylandtlaan 16",
    to: "Amsterdam Schiphol, Terminal 3",
    vehicle: "Sedan",
    stage: "New",
    amount: 145,
    owner: "Piet",
    nextAction: "Confirm flight number and wait-time cap",
    nextActionDate: "2026-09-15",
    lostReason: "",
    notes: "",
    log: [
      log("lg5", "2026-09-13", "Incoming", "Email", "Airport drop-off 19 Sep, two execs, flight KL 1006 12:40."),
    ],
    created: "2026-09-13",
    moved: "2026-09-13",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "q_event",
    ref: "Q-0015",
    brand: "HollandCoach.nl",
    source: "Website",
    company: "Eventure MICE",
    contactName: "Mila de Boer",
    contactEmail: "mila@eventure.nl",
    contactPhone: "+31 6 4871 2209",
    tripDate: "2026-10-03",
    pax: 28,
    from: "RAI Amsterdam",
    to: "Kurhaus, Scheveningen",
    vehicle: "Midi coach 35",
    stage: "Qualified",
    amount: 740,
    owner: "Anouk",
    nextAction: "Site visit / load-in window with Kurhaus",
    nextActionDate: "2026-09-20",
    lostReason: "",
    notes: "Gala shuttle, two runs.",
    log: [
      log("lg6", "2026-09-08", "Outgoing", "Phone call", "Qualified: 28 pax, two shuttles, evening dress-code so coach must be clean-glass."),
    ],
    created: "2026-09-07",
    moved: "2026-09-08",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "q_lost",
    ref: "Q-0011",
    brand: "Schengen Holidays",
    source: "Website",
    company: "Unilever Nederland",
    contactName: "Facilities desk",
    contactEmail: "ap@unilever.com",
    contactPhone: "+31 10 439 4911",
    tripDate: "2026-09-05",
    pax: 40,
    from: "Rotterdam Weena",
    to: "Brussels Midi",
    vehicle: "Coach 50",
    stage: "Lost",
    amount: 1450,
    owner: "Anouk",
    nextAction: "",
    nextActionDate: "",
    lostReason: "Price too high",
    notes: "Went with a Belgian operator.",
    log: [
      log("lg7", "2026-09-02", "Incoming", "Email", "Thanks, we have placed this with a Brussels carrier."),
      log("lg8", "2026-08-28", "Outgoing", "Email", "Sent quote €1.450 excl. for day return."),
    ],
    created: "2026-08-27",
    moved: "2026-09-02",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "q_won_wedding",
    ref: "Q-0010",
    brand: "GS Tours",
    source: "Referral",
    company: "Sophie van Dijk",
    contactName: "Sophie van Dijk",
    contactEmail: "sophie.vandijk@icloud.com",
    contactPhone: "+31 6 2188 4401",
    tripDate: "2026-09-20",
    pax: 14,
    from: "Prins Hendrikstraat 18, Den Haag",
    to: "Kasteel De Wittenburg, Wassenaar",
    vehicle: "Minibus 19",
    stage: "Won",
    amount: 680,
    owner: "Anouk",
    nextAction: "",
    nextActionDate: "",
    lostReason: "",
    notes: "Converted to B-0009.",
    log: [
      log("lg9", "2026-09-04", "Incoming", "WhatsApp", "Yes please, go ahead — cream ribbon on the grille if you can."),
      log("lg10", "2026-09-01", "Outgoing", "Email", "Quote for wedding transfer + evening return."),
    ],
    created: "2026-08-30",
    moved: "2026-09-04",
    updatedAt: AT,
    updatedBy: BY,
  },
];

const bookings: BookingRecord[] = [
  {
    id: "b_india",
    ref: "B-0008",
    brand: "GS Tours",
    status: "Confirmed",
    tripType: "Day trip (dagtocht)",
    company: "Embassy of India",
    contactName: "Mr. R. Kumar",
    contactPhone: "+31 70 346 9771",
    dates: [
      { date: "2026-09-18", endDate: "2026-09-18", pickupTime: "08:00", returnTime: "18:00", note: "DDG programme" },
    ],
    from: "Buitenrustweg 2, Den Haag",
    to: "Ministries round",
    returnFrom: "",
    pax: 3,
    units: [
      {
        vehicle: "Sedan",
        plate: "GS-01-NL",
        driver: "Piet van Leeuwen",
        driver2: "",
        pax: 3,
        cost: 0,
        subcontractor: "",
      },
    ],
    groupLeader: "Mr. R. Kumar",
    groupLeaderPhone: "+31 70 346 9771",
    amount: 550,
    paid: "Not invoiced",
    reference: "HAG/873/2/2021",
    notes: "Tender vehicle: S-Class or XC90.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "b_india_van",
    ref: "B-0011",
    brand: "GS Tours",
    status: "Confirmed",
    tripType: "Day trip (dagtocht)",
    company: "Embassy of India",
    contactName: "Mr. R. Kumar",
    contactPhone: "+31 70 346 9771",
    dates: [
      { date: "2026-09-18", endDate: "2026-09-18", pickupTime: "08:30", returnTime: "17:00", note: "Spouse programme" },
    ],
    from: "Buitenrustweg 2, Den Haag",
    to: "Madurodam / Delft",
    returnFrom: "",
    pax: 5,
    units: [
      {
        vehicle: "MPV / Van",
        plate: "GS-01-NL",
        driver: "Farid El Idrissi",
        driver2: "",
        pax: 5,
        cost: 0,
        subcontractor: "",
      },
    ],
    groupLeader: "Ms. Sharma",
    groupLeaderPhone: "",
    amount: 610,
    paid: "Not invoiced",
    reference: "HAG/873/2/2021",
    notes: "SAME PLATE as B-0008 — hard conflict on 18 Sep, needs a second car.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "b_wedding",
    ref: "B-0009",
    brand: "GS Tours",
    status: "Confirmed",
    tripType: "Wedding / event",
    company: "Sophie van Dijk",
    contactName: "Sophie van Dijk",
    contactPhone: "+31 6 2188 4401",
    dates: [
      { date: "2026-09-20", endDate: "2026-09-20", pickupTime: "13:00", returnTime: "23:30", note: "Ceremony + evening return" },
    ],
    from: "Prins Hendrikstraat 18, Den Haag",
    to: "Kasteel De Wittenburg, Wassenaar",
    returnFrom: "Kasteel De Wittenburg",
    pax: 14,
    units: [
      {
        vehicle: "Minibus 19",
        plate: "GS-19-HZ",
        driver: "Piet van Leeuwen",
        driver2: "",
        pax: 14,
        cost: 0,
        subcontractor: "",
      },
    ],
    groupLeader: "Sophie van Dijk",
    groupLeaderPhone: "+31 6 2188 4401",
    amount: 680,
    paid: "Invoiced",
    reference: "",
    notes: "Cream ribbon. No confetti inside the vehicle.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "b_wedding_dup",
    ref: "B-0012",
    brand: "GS Tours",
    status: "Confirmed",
    tripType: "Wedding / event",
    company: "Sophie van Dijk",
    contactName: "Sophie van Dijk",
    contactPhone: "+31 6 2188 4401",
    dates: [
      { date: "2026-09-20", endDate: "2026-09-20", pickupTime: "13:00", returnTime: "23:30", note: "Possible duplicate of B-0009" },
    ],
    from: "Prins Hendrikstraat 18, Den Haag",
    to: "Kasteel De Wittenburg, Wassenaar",
    returnFrom: "",
    pax: 14,
    units: [
      {
        vehicle: "Minibus 19",
        plate: "",
        driver: "",
        driver2: "",
        pax: 14,
        cost: 0,
        subcontractor: "",
      },
    ],
    groupLeader: "",
    groupLeaderPhone: "",
    amount: 680,
    paid: "Not invoiced",
    reference: "",
    notes: "Entered a second time from a WhatsApp forward — likely duplicate of B-0009.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "b_tour",
    ref: "B-0010",
    brand: "Schengen Holidays",
    status: "Confirmed",
    tripType: "Multi-day tour",
    company: "Hotel Des Indes",
    contactName: "Concierge",
    contactPhone: "+31 70 361 2345",
    dates: [
      {
        date: "2026-09-22",
        endDate: "2026-09-24",
        pickupTime: "08:30",
        returnTime: "18:00",
        note: "Bruges — Ghent — Antwerp",
      },
    ],
    from: "Lange Voorhout 54, Den Haag",
    to: "Belgium circuit",
    returnFrom: "Lange Voorhout 54, Den Haag",
    pax: 32,
    units: [
      {
        vehicle: "Midi coach 35",
        plate: "GS-35-BH",
        driver: "Jan Bakker",
        driver2: "Farid El Idrissi",
        pax: 32,
        cost: 0,
        subcontractor: "",
      },
    ],
    groupLeader: "Hotel Des Indes concierge",
    groupLeaderPhone: "+31 70 361 2345",
    amount: 2850,
    paid: "Not invoiced",
    reference: "DI-2026-0922",
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "b_corendon",
    ref: "B-0013",
    brand: "BusBus.nl",
    status: "Confirmed",
    tripType: "Day trip (dagtocht)",
    company: "Corendon Travel",
    contactName: "Lisa Vermeer",
    contactPhone: "+31 6 1092 4410",
    dates: [
      { date: "2026-09-22", endDate: "2026-09-22", pickupTime: "09:00", returnTime: "16:30", note: "" },
    ],
    from: "Schiphol Plaza",
    to: "Keukenhof, Lisse",
    returnFrom: "Keukenhof, Lisse",
    pax: 48,
    units: [
      {
        vehicle: "Coach 50",
        plate: "GS-50-KK",
        driver: "Saskia Moens",
        driver2: "",
        pax: 48,
        cost: 0,
        subcontractor: "",
      },
    ],
    groupLeader: "Lisa Vermeer",
    groupLeaderPhone: "+31 6 1092 4410",
    amount: 980,
    paid: "Not invoiced",
    reference: "COR-KEU-0922",
    notes: "Same day as B-0010 midi — soft signal only (different vehicle type).",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "b_done",
    ref: "B-0007",
    brand: "HollandCoach.nl",
    status: "Completed",
    tripType: "Airport transfer",
    company: "British Embassy The Hague",
    contactName: "Transport desk",
    contactPhone: "+31 70 427 0427",
    dates: [
      { date: "2026-09-08", endDate: "2026-09-08", pickupTime: "06:40", returnTime: "08:10", note: "" },
    ],
    from: "Lange Voorhout 10",
    to: "Amsterdam Schiphol",
    returnFrom: "",
    pax: 2,
    units: [
      {
        vehicle: "Sedan",
        plate: "GS-01-NL",
        driver: "Piet van Leeuwen",
        driver2: "",
        pax: 2,
        cost: 0,
        subcontractor: "",
      },
    ],
    groupLeader: "",
    groupLeaderPhone: "",
    amount: 160,
    paid: "Paid",
    reference: "",
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
];

const invoices: InvoiceRecord[] = [
  {
    id: "in_india",
    number: "2026-0008",
    type: "normal",
    originalId: "",
    status: "Sent",
    date: "2026-09-10",
    dueDate: "2026-10-10",
    company: "Embassy of India",
    contactName: "Mr. R. Kumar",
    address: "Buitenrustweg 2, 2517 KD Den Haag",
    clientBtw: "",
    billPrivate: false,
    reference: "HAG/873/2/2021 — August programme",
    lines: [
      {
        id: "il1",
        date: "2026-08-12",
        desc: "For Mr. Kumar: Full Day hire — Sedan, 08:00–16:40, 8.7h / 94 km",
        qty: 1,
        unitPrice: 550,
        vat: "9",
      },
      {
        id: "il2",
        date: "2026-08-07",
        desc: "For Ms. Sharma: Half Day hire — Minivan, 09:00–14:10, 5.2h / 48 km",
        qty: 1,
        unitPrice: 320,
        vat: "9",
      },
      {
        id: "il3",
        date: "2026-08-19",
        desc: "For Mr. Kumar: Extra kilometres — 22 km beyond 120 km allowance",
        qty: 22,
        unitPrice: 1,
        vat: "9",
      },
    ],
    amountPaid: 0,
    paidDate: "",
    sendTo: "cons.thehague@mea.gov.in",
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "in_wedding",
    number: "2026-0009",
    type: "normal",
    originalId: "",
    status: "Draft",
    date: "2026-09-12",
    dueDate: "2026-09-19",
    company: "Sophie van Dijk",
    contactName: "Sophie van Dijk",
    address: "Prins Hendrikstraat 18, 2518 HZ Den Haag",
    clientBtw: "",
    billPrivate: true,
    reference: "Wedding 20 September",
    lines: [
      {
        id: "il4",
        date: "2026-09-20",
        desc: "Minibus 19 — wedding transfer Den Haag to Kasteel De Wittenburg and evening return",
        qty: 1,
        unitPrice: 680,
        vat: "9",
      },
    ],
    amountPaid: 0,
    paidDate: "",
    sendTo: "sophie.vandijk@icloud.com",
    notes: "Private individual — omit VAT number on the PDF.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "in_overdue",
    number: "2026-0006",
    type: "normal",
    originalId: "",
    status: "Reminded",
    date: "2026-08-01",
    dueDate: "2026-08-15",
    company: "Eventure MICE",
    contactName: "Mila de Boer",
    address: "Weteringschans 165, 1017 XD Amsterdam",
    clientBtw: "NL8544.21.009.B01",
    billPrivate: false,
    reference: "Pride shuttle July",
    lines: [
      {
        id: "il5",
        date: "2026-07-18",
        desc: "Midi coach 35 — Amsterdam evening shuttle",
        qty: 1,
        unitPrice: 740,
        vat: "9",
      },
    ],
    amountPaid: 0,
    paidDate: "",
    sendTo: "billing@eventure.nl",
    notes: "Second reminder sent 1 Sep.",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "in_paid",
    number: "2026-0005",
    type: "normal",
    originalId: "",
    status: "Paid",
    date: "2026-08-20",
    dueDate: "2026-09-03",
    company: "British Embassy The Hague",
    contactName: "Transport desk",
    address: "Lange Voorhout 10, 2514 ED Den Haag",
    clientBtw: "",
    billPrivate: false,
    reference: "",
    lines: [
      {
        id: "il6",
        date: "2026-08-12",
        desc: "Sedan — Schiphol arrival transfer",
        qty: 1,
        unitPrice: 160,
        vat: "9",
      },
    ],
    amountPaid: 174.4,
    paidDate: "2026-08-28",
    sendTo: "ukinnl.finance@fcdo.gov.uk",
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "in_credit",
    number: "2026-0007",
    type: "credit",
    originalId: "in_overdue",
    status: "Credited",
    date: "2026-08-22",
    dueDate: "2026-08-22",
    company: "Eventure MICE",
    contactName: "Mila de Boer",
    address: "Weteringschans 165, 1017 XD Amsterdam",
    clientBtw: "NL8544.21.009.B01",
    billPrivate: false,
    reference: "Credit against 2026-0006 — cancelled second run",
    lines: [
      {
        id: "il7",
        date: "2026-07-18",
        desc: "Credit — cancelled second shuttle run",
        qty: 1,
        unitPrice: -200,
        vat: "9",
      },
    ],
    amountPaid: 0,
    paidDate: "",
    sendTo: "billing@eventure.nl",
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "in_gemeente",
    number: "2026-0004",
    type: "normal",
    originalId: "",
    status: "Partly paid",
    date: "2026-07-15",
    dueDate: "2026-08-14",
    company: "Gemeente Den Haag",
    contactName: "Inkoop Mobiliteit",
    address: "Spui 70, 2511 BT Den Haag",
    clientBtw: "NL0016.90.962.B01",
    billPrivate: false,
    reference: "PO 2026-4410",
    lines: [
      {
        id: "il8",
        date: "2026-07-02",
        desc: "Coach 50 — city council outing Scheveningen",
        qty: 1,
        unitPrice: 920,
        vat: "9",
      },
      {
        id: "il9",
        date: "2026-07-02",
        desc: "Extra hours",
        qty: 2,
        unitPrice: 55,
        vat: "9",
      },
    ],
    amountPaid: 500,
    paidDate: "2026-08-01",
    sendTo: "facturen@denhaag.nl",
    notes: "",
    updatedAt: AT,
    updatedBy: BY,
  },
];

const drivers: DriverRecord[] = [
  {
    id: "dr_piet",
    name: "Piet van Leeuwen",
    phone: "+31 6 5122 8841",
    email: "piet@gstours.nl",
    license: "D / D1",
    notes: "Lead chauffeur. Embassy-cleared.",
    hours: [
      {
        id: "hr1",
        date: "2026-09-14",
        start: "07:00",
        end: "16:30",
        bookingRef: "B-0008",
        vehicle: "GS-01-NL",
        notes: "Prep + standby for Friday embassy run",
      },
      {
        id: "hr2",
        date: "2026-09-18",
        start: "07:30",
        end: "18:30",
        bookingRef: "B-0008",
        vehicle: "GS-01-NL",
        notes: "DDG programme",
      },
      {
        id: "hr3",
        date: "2026-09-20",
        start: "12:00",
        end: "23:45",
        bookingRef: "B-0009",
        vehicle: "GS-19-HZ",
        notes: "Wedding transfer + evening return",
      },
    ],
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "dr_farid",
    name: "Farid El Idrissi",
    phone: "+31 6 2291 4403",
    email: "farid@gstours.nl",
    license: "B / D1",
    notes: "Van and sedan. Speaks NL / FR / AR.",
    hours: [
      {
        id: "hr4",
        date: "2026-09-15",
        start: "06:30",
        end: "14:00",
        bookingRef: "",
        vehicle: "GS-01-NL",
        notes: "Schiphol early pair",
      },
      {
        id: "hr5",
        date: "2026-09-18",
        start: "08:00",
        end: "17:15",
        bookingRef: "B-0011",
        vehicle: "GS-01-NL",
        notes: "Spouse programme — plate conflict with Piet, needs a second car",
      },
    ],
    updatedAt: AT,
    updatedBy: BY,
  },
];

const vehicles: VehicleRecord[] = [
  {
    id: "vh_sedan",
    plate: "GS-01-NL",
    kind: "Sedan",
    make: "Mercedes-Benz",
    model: "E-Class",
    year: "2023",
    motUntil: "2026-11-18",
    insuranceUntil: "2026-10-01",
    notes: "Embassy-cleared. Hard plate conflict on 18 Sep — do not double-book.",
    log: [
      {
        id: "mt1",
        date: "2026-06-12",
        kind: "Service",
        km: 48210,
        vendor: "Mercedes Den Haag",
        cost: 640,
        notes: "A-service + cabin filter",
      },
      {
        id: "mt2",
        date: "2026-08-04",
        kind: "Tyres",
        km: 51002,
        vendor: "KwikFit Loosduinen",
        cost: 780,
        notes: "Four Michelin Primacy 4",
      },
    ],
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "vh_mini",
    plate: "GS-19-HZ",
    kind: "Minibus 19",
    make: "Mercedes-Benz",
    model: "Sprinter",
    year: "2021",
    motUntil: "2026-08-22",
    insuranceUntil: "2027-01-15",
    notes: "Wedding ribbon kit in the boot. APK overdue — book this week.",
    log: [
      {
        id: "mt3",
        date: "2026-08-22",
        kind: "APK",
        km: 128440,
        vendor: "RDW erkende garage",
        cost: 62,
        notes: "Failed on rear brake discs — repair booked.",
      },
      {
        id: "mt4",
        date: "2026-09-01",
        kind: "Repair",
        km: 128510,
        vendor: "Bosch Car Service",
        cost: 890,
        notes: "Rear discs + pads. Re-test pending.",
      },
    ],
    updatedAt: AT,
    updatedBy: BY,
  },
  {
    id: "vh_coach",
    plate: "GS-50-HZ",
    kind: "Coach 50",
    make: "Setra",
    model: "S 515 HD",
    year: "2019",
    motUntil: "2027-03-04",
    insuranceUntil: "2026-12-31",
    notes: "Toilet coach. Keep Keukenhof parking permit in glovebox.",
    log: [
      {
        id: "mt5",
        date: "2026-05-20",
        kind: "Service",
        km: 312000,
        vendor: "EVOBUS Nederland",
        cost: 2140,
        notes: "Major service",
      },
    ],
    updatedAt: AT,
    updatedBy: BY,
  },
];

export function sampleWorkspace(): Workspace {
  return {
    companies,
    vendors,
    contacts,
    queries,
    bookings,
    invoices,
    drivers,
    vehicles,
    settings: { ...DEFAULT_SETTINGS, nextNumber: 10 },
    meta: { qSeq: 15, bSeq: 13 },
  };
}

export function sampleCounts() {
  return {
    companies: companies.length,
    vendors: vendors.length,
    contacts: contacts.length,
    queries: queries.length,
    bookings: bookings.length,
    invoices: invoices.length,
    drivers: drivers.length,
    vehicles: vehicles.length,
  };
}
